# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REF_RTX', '0002_auto_20170911_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtx_infusion',
            name='no_of_infusion',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
