# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REF_RTX', '0003_auto_20170914_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='infusion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtx_infusion', to='REF_RTX.rtx_infusion'),
        ),
    ]
