# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REF_RTX', '0004_auto_20170914_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtx_infusion',
            name='no_of_infusion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
