# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REF_RTX', '0005_auto_20170914_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtx_infusion',
            name='no_of_infusion',
            field=models.IntegerField(unique=True),
        ),
    ]
