# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('REF_RTX', '0006_auto_20170915_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtx_infusion',
            name='schedule_followup_date',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_email',
            field=models.EmailField(max_length=254, verbose_name='Doctor Email'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='ANCA_titre',
            field=models.FloatField(blank=True, null=True, verbose_name='ANCA Titre'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='CRP',
            field=models.FloatField(blank=True, null=True, verbose_name='CRP'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='ESR',
            field=models.FloatField(blank=True, null=True, verbose_name='ESR'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='MPO_titre',
            field=models.FloatField(blank=True, null=True, verbose_name='MPO Titre'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='PR3_titre',
            field=models.FloatField(blank=True, null=True, verbose_name='PR3 Titre'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='cd19_abs_count',
            field=models.FloatField(blank=True, null=True, verbose_name='CD19 abs Count'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='creatinine',
            field=models.FloatField(blank=True, null=True, verbose_name='Creatinine'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='followup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Followup Date'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='infusion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rtx_infusion', to='REF_RTX.rtx_infusion', verbose_name='Infusion No'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='serum_albumin',
            field=models.FloatField(blank=True, null=True, verbose_name='Serum Albumin'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='type',
            field=models.CharField(blank=True, choices=[('PRE-RTX', 'PRE-RTX'), ('RTX-3 Monthes', 'RTX-3M'), ('RTX-6 Monthes', 'RTX-6M'), ('RTX-9 Monthes', 'RTX-9M'), ('RTX-12 Monthes', 'RTX-12M'), ('RTX-15 Monthes', 'RTX-15M'), ('RTX-18 Monthes', 'RTX-18M'), ('RTX-21 Monthes', 'RTX-21M'), ('RTX-24 Monthes', 'RTX-24M'), ('RTX-27 Monthes', 'RTX-27M'), ('RTX-30 Monthes', 'RTX-30M')], max_length=50, null=True, verbose_name='Infusion Type'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='upcr',
            field=models.FloatField(blank=True, null=True, verbose_name='UPCR'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='urine_rbc',
            field=models.CharField(blank=True, choices=[('< 10', '< 10'), ('10 - 100', '10 - 100'), ('> 100', '> 100')], max_length=50, null=True, verbose_name='Urine RBC'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DOB',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Diagnosis_subtype',
            field=models.CharField(blank=True, choices=[('Lupus Nephritis', (('Class3', 'Class3'), ('Class4', 'Class4'), ('Class5', 'Class5'), ('Class3 and Class5', 'Class3 and Class5'), ('Class4 and Class5', 'Class4 and Class5'))), ('Vasculitis', (('ANCA MPO', 'ANCA MPO'), ('ANCA PR3', 'ANCA PR3'), ('ANCA -VE', 'ANCA -VE'), ('Other', 'Other'))), ('Nephrotic Syndrome', (('Minimal Change', 'Minimal Change'), ('FSGS', 'FSGS'), ('Membranous', 'Membranous')))], max_length=200, null=True, verbose_name='Diagnsis Subtype'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Diagnosis_type',
            field=models.CharField(blank=True, choices=[('Lupus Nephritis', 'Lupus Nephritis'), ('Vasculitis', 'Vasculitis'), ('Nephrotic Syndrome', 'Nephrotic Syndrome'), ('MPGN', 'MPGN')], default='Nephrotic Syndrome', max_length=200, null=True, verbose_name='Diagnsis Type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Previous_treatment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Prednisolone', 'Prednisolone'), ('Tacrolimus', 'Tacrolimus'), ('Mycophenolate', 'Mycophenolate'), ('Cyclosporin', 'Cyclosporin'), ('Cyclophosphamide', 'Cyclophosphamide'), ('Azathioprine', 'Azathioprine'), ('Methotrexate', 'Methotrexate'), ('Rituximab', 'Rituximab'), ('Other', 'Other')], max_length=108, verbose_name='Previous Treatment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_diagnosis',
            field=models.DateField(verbose_name='Date of Diagnosis'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pre_rtx_comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pre RTX Comment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pre_rtx_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pre RTX Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prev_other_comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pre Other'),
        ),
        migrations.AlterField(
            model_name='rtx_infusion',
            name='concomitant_immunosuppression',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Prednisolone', 'Prednisolone'), ('Tacrolimus', 'Tacrolimus'), ('Mycophenolate', 'Mycophenolate'), ('Cyclosporin', 'Cyclosporin'), ('Cyclophosphamide', 'Cyclophosphamide'), ('Azathioprine', 'Azathioprine'), ('Methotrexate', 'Methotrexate'), ('Rituximab', 'Rituximab'), ('Other', 'Other')], max_length=108, verbose_name='Concomitant IS'),
        ),
        migrations.AlterField(
            model_name='rtx_infusion',
            name='date_of_infusion',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Infusion'),
        ),
        migrations.AlterField(
            model_name='rtx_infusion',
            name='dose_in_mg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dose in gms'),
        ),
        migrations.AlterField(
            model_name='rtx_infusion',
            name='no_of_infusion',
            field=models.IntegerField(unique=True, verbose_name='Infusion No'),
        ),
    ]
