# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REF_RTX', '0007_auto_20170915_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='type',
            field=models.CharField(blank=True, choices=[('PRE-RTX', 'PRE-RTX'), ('RTX-1 Monthes', 'RTX-1M'), ('RTX-3 Monthes', 'RTX-3M'), ('RTX-6 Monthes', 'RTX-6M'), ('RTX-9 Monthes', 'RTX-9M'), ('RTX-12 Monthes', 'RTX-12M'), ('RTX-1.5 Years', 'RTX-1.5Y'), ('RTX-2 Years', 'RTX-2Y'), ('RTX-3 Years', 'RTX-3Y'), ('RTX-4 Years', 'RTX-4Y'), ('RTX-5 Years', 'RTX-5Y'), ('RTX-6 Years', 'RTX-6Y')], max_length=50, null=True, verbose_name='Infusion Type'),
        ),
    ]
