# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REF_RTX', '0008_auto_20170915_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Test Date'),
        ),
    ]
